@startuml

class Assistant

class DialogManager {
  Gère le dialogue complet
  ----
  +NLU nlu
  +Input in
  +Output out
  +checkSyntax(Input in)
  +checkSemantic(List<Tag>)
  +answer()
  +askConfirmation()
  +analyze()
}

class NLU {
  Analyse le texte
  ----
  +List<Tag> tags
  +parseSyntax(String str)
  +parseSemantic(List<Tag> tags)
}

class Tag{
  +String value
  +String label
}

class Input {
  +String inputText
}

class Output {
  +String outputText
}

class Alarm {
    +time
    +volume
}

class Location {
    +latitude
    +longitude
}

enum Weather {
    +SUNNY
    +RAINY
    +CLOUDY
    +...
}

class SoundPlayer
class Sound

class Action {
}

Location "*"--"1" Weather
Alarm "*"--"1" Sound
Sound "*"-left-"1" SoundPlayer
Assistant *-- Alarm
Assistant *-- Location
Assistant *-- DialogManager
DialogManager *--NLU
DialogManager *-- Input
DialogManager *-- Output
NLU -- Tag

@enduml
