@startuml

title Use Case Diagram 
left to right direction

actor :User: as user

rectangle System {
    actor :Assistant: as agent #black
    
    (Dialog to program an alarm) as usecase0
    (Program an alarm to a defined hour) as usecase1
    user -right- usecase0
    agent -- usecase1
    agent -- usecase0
    
    usecase1 .> (Program alarm) : <<include>>
    (Program alarm) .-> (Get location) : <<include>>
    (Program alarm) .-> (Get weather) : <<include>>
    (Program alarm) .-> (Set sound) : <<include>>
}
@enduml
